name: tests

on:
  workflow_call:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        redis: ["7", "6"]

    services:
      redis:
        image: redis:${{ matrix.redis }}
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    name: PHP 8.3 Laravel 11 with Redis ${{ matrix.redis }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: redis
          tools: composer:v2
          ini-values: error_reporting=E_ALL

      - name: Set Laravel version
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require illuminate/redis:^11 --dev --no-interaction --no-update

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress

      - name: Execute bench
        run: make bench
